### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by medienbaecker** [medienbaecker/kirby-images#1]
"No entries yet." comes from the structure field and is not an ideal description. Maybe it should also explain that drag-and-drop is possible.

**Comment by jenstornell** [comment]
"Drop or select an image" would be nice I think.

I suggest you wait with this one until this feature is added:
https://github.com/getkirby/kirby/issues/532

**Comment by medienbaecker** [comment]
As this feature still seems to take some time I have added translations another way.
