### ISSUE TITLE
Automatically remove images whose files are removed from the page

### ISSUE THREAD

**Issue by dkerzig** [medienbaecker/kirby-images#13]
Hey, 
first thanks for this amazing panel-field! I like how easy it is.

Maybe the behavior could be even improved by reacting on panel-hooks which are fired when an image is removed from the panel. If it is included in the gallery-array it should be removed there (it actually is removed in the panel but not from the markdown-file).

Regards from Germany,
Dennis

**Comment by medienbaecker** [comment]
Hey Dennis,

thank you, I'm glad you like this field!
I totally see what you mean. The plugin just skipped the images it couldn't find in the files pool.

I just changed some things and now removed images are not saved to the field value anymore. Just remember you have to save again after removing an image as I don't think it would be good to trigger another save after every image deletion.

**Comment by dkerzig** [comment]
Nice, this was fast :)

FYI these are the helper functions I use to extract the actual image-object. 

<img width="557" alt="bildschirmfoto 2017-05-23 um 11 23 44" src="https://cloud.githubusercontent.com/assets/3930150/26347610/645a45b0-3faa-11e7-83f6-05ea0a2b3529.png">

**Comment by medienbaecker** [comment]
Wow, that looks fancy. Why don't you simply use something like

```php
<?php foreach($page->slideshow()->yaml() as $image): ?>   
  <?php if($image = $page->image($image)): ?>
    <?= $image->crop(1200,500)->html(); ?>  		    
  <?php endif ?>
<?php endforeach; ?>
```

`$page->image()` returns an image object, too. But maybe I overlooked something in your code.

**Comment by dkerzig** [comment]
Yes this looks much simpler but I need

- A way to know in advance if there is at least one image associated (an image-object could be null even if `slideshow` is not empty)
- and an array of actual image-objects as input-parameter for my gallery-snippet

But thanks anyway 🙏

**Comment by medienbaecker** [comment]
Ah, alright. Then you are definitely allowed to use that 😉
