### ISSUE TITLE
Bug when dragging image

### ISSUE THREAD

**Issue by jenstornell** [medienbaecker/kirby-images#15]
Steps to reproduce:

1. Drag an image to sort it with your field. Make sure to hover the remove button when dragging it.
1. When dropping it it will be sorted correctly, but then the image will also be removed.

While it is correct from a technical perspective it's not very user friendly, Looking at the "Files" in the panel the image is not removed even when dragging with the trash button.

For some reason the edit button works like expected (not getting edited on drag).

**Comment by medienbaecker** [comment]
Thanks Jens! That's definitely not very user friendly. I never dragged on the "Remove" button but I could reproduce it and just pushed a commit to fix this issue.
Now it first looks for the `.ui-sortable-helper` class that gets added when dragging an image.
