### ISSUE TITLE
Remove margin bottom from empty

### ISSUE THREAD

**Issue by jenstornell** [medienbaecker/kirby-images#17]
`.field-with-images .files .empty` has `margin-bottom: 1.5em;`. It's not needed because the margin bottom is handled by the `.field` class.

I'm reporting this by selfish reasons as well. In my engineer field I have empty sections as well and here we can see the gap very clear.

![image](https://user-images.githubusercontent.com/927011/26935092-56ea7508-4c6b-11e7-992e-b8db71d97e5a.png)

In case you wonder what it is, it's 3 fields where the first is your `images` field. The next two are nested empty engineer fields.

**Comment by medienbaecker** [comment]
I just removed the margin, don't know why it was there in the first place. Thanks Jens!
