### ISSUE TITLE
Store as a yaml list directly?

### ISSUE THREAD

**Issue by jenstornell** [medienbaecker/kirby-images#18]
This is more of a question than a feature request.

My Engineer field works with almost very built in field and even some plugins out of the box. With the Images plugin I needed to add a trigger to refresh the DOM when adding a new item but it's a oneliner so I think it's fine to do that in Engineer.

Another thing is that you use `result()` to convert a json string to a yaml string. Because Engineer doesn't use Ajax it just saves the json, not the yaml.

Is it possible to add the data as yaml directly? It would probably work with a hidden field or a hidden textarea.

If you think it's the wrong approach, I'm fine with that as well.

**Comment by medienbaecker** [comment]
I do use a hidden field that stores the data in its `value` attribute.
I'll try putting the yaml data directly in there, if that helps you with the compatibility with the engineer field. Not sure if that works, though...

**Comment by medienbaecker** [comment]
I just changed the `results()` function and now the field directly stores the `yaml` in the hidden input: https://github.com/medienbaecker/kirby-images/tree/yaml

Does this work for you? I'll test it too and then merge it to master.

**Comment by jenstornell** [comment]
Great! I can confirm that it still works without Engineer and that it does not yet work with Engineer.

I think it has to do that I probably forgot to add support for the `hidden` input field type. I will look into it right away. I write again when I can confirm that it works on my side as well.

**You can remove this code as well:**

```php
public function result() {
  $result = parent::result();
  return $result;
}
```

`result()` is run by the basefield if not exists so this function above does nothing right now.

But anyway, I'll get back to this today...

**Comment by jenstornell** [comment]
I have a solution now on localhost. It works great, but there is one more thing I need for it to work. I've added a pull request. The input hidden does not trigger an event in jQuery so I added a change trigger.

If you accept the pull request you can also close this issue if you want. I will release the new Engineer field version today or later this week.

**Comment by medienbaecker** [comment]
Thanks a lot, Jens! I just pushed the changes to the master branch.
