### ISSUE TITLE
Major issue about loading

### ISSUE THREAD

**Issue by jenstornell** [medienbaecker/kirby-images#22]
I tried to add, save and see if the images was loaded correctly and they were.

What I did not check was what happend when I saved again without a change to the images. They disapear, not only in Engineer but as a field as well.

The problem is that when they are loaded they are separated by comma in the input like `image1.jpg,image2.jpg`.

I also found out that it does not really matter if it's json or yaml because I still need to add a few rows of js to get the field to work (sorry if I complicated things).

Anyway if you change the loaded output to yaml it should work.

**Comment by medienbaecker** [comment]
I overlooked one part where I still separate the values by comma. It's fixed now. Sorry!

**Comment by jenstornell** [comment]
I can confirm that it works now, both as single field and inside Engineer. 👍

**Comment by medienbaecker** [comment]
Perfect! I still haven't found the time to have a more in depth look at the Engineer field. It looks very promising though!
