### ISSUE TITLE
width: 2/3 problem

### ISSUE THREAD

**Issue by jenstornell** [medienbaecker/kirby-images#23]
The width 2/3 comes with trouble with some resolutions (not all). It appears it's an issue in general, not just for Engineer. The images field on top is without Engineer.

```text
images:
    label: Images
    type: images
    width: 2/3
```

![image](https://user-images.githubusercontent.com/927011/27588148-6e07d722-5b47-11e7-9e19-4fd79a05ec91.png)

**Comment by medienbaecker** [comment]
With `trouble` you mean that the grid items are too small? I plan to decouple the fields CSS from the Kirby core CSS and completely rewrite it using flexbox, anyway.

Or is it something else?

**Comment by jenstornell** [comment]
Ahh! It's just me. Now I understand how it works. In this mode it displays 4 in a row.

![image](https://user-images.githubusercontent.com/927011/27589357-6e3eac76-5b4b-11e7-8a1f-1c550d324da3.png)

But maybe this is a bit two narrow to have 4 images in a row? It's probably an edge case but 3 images would probably look better in this screen resolution.

**Comment by medienbaecker** [comment]
Yeah, that's exactly what I've planned.
I relied on the full page image grid CSS, which is not ideal sometimes.

After I have rewritten the styles it will use the given space better.

**Comment by jenstornell** [comment]
The Engineer will always be more narrow because of it's wrapped in nature, but if it looks good as a normal field it will be at least ok in the first Engineer level. If there is nesting with Engineer, the user should probably not use 2/3.

In conclusion, maybe just fix the css just for the field level. Then the Engineer field will probably be fine.

Thanks!
