### ISSUE TITLE
Force set number of images on each row

### ISSUE THREAD

**Issue by jenstornell** [medienbaecker/kirby-images#24]
It's great that it tries to create the best image gallery depending on the screen resolution. Media queries still have their limitations. They can't feel the width of a div for example.

In my latest version that I will release there is a kind of a grid support where `width` is supported not only on the fields, but on the `engineer` field as well, which is like the container of the fields.

**Here is an example where I've set `width: 1/3`.**

![kirby starterkit panel](https://user-images.githubusercontent.com/927011/27685603-43d3f470-5ccf-11e7-9af8-839ede48e5c1.png)

I think it came out great, except the images field could not keep up. Because of nesting it would be impossible I would say for the images field to know how many images there could be before it looks weird.

### Possible simple solution

```text
fields:
  images:
    type: images
    fit: 1
```

In this case I set `fit: 1` which means 1 image on each row. Maximum could be like 5 or something.

Maybe there is a better name for it but it could be a bit long like `numberOfImagesOnEachRow: 1`.

The best way to do it would be to add a class which overrides the css when fit is set like `images-fit-1`.

What do you think about the idea and the solution for it?

**Comment by medienbaecker** [comment]
Right now I'm experimenting with https://github.com/marcj/css-element-queries to solve that problem.

**Comment by jenstornell** [comment]
I've read about it, but I have some trust issues with it (but I have never tried it out).

>Well, since the query no longer matches, the new width is no longer applied. Since that new width is never applied, the element query would match again, so the new width would be applied, so the query would no longer match, so the new width wouldn’t be applied—and so on unto infinity. We've achieved a TARDIS-caliber paradox with just a few lines of CSS, and there's no predictable way for the browser to handle it.

**Source:** https://css-tricks.com/container-queries-once-more-unto-the-breach/

Anyway, if you get it to work with that, it's totally fine by me. In fact, I really hope you get it to work with it. =)

**Comment by medienbaecker** [comment]
I think that will not be an issue as the images do not define the containers width, therefore not causing an infinite loop.
I initially also thought of the manually set option, but it really depends on not only the field location (inside an engineer field for example) but also on the screen size.

**Comment by olach** [comment]
This would be a perfect example of using the new CSS grids.

See this example:
https://gridbyexample.com/examples/example28/

Browser support is all the evergreen browsers. A simple fallback with static widths for the images would be good enough.

**Comment by medienbaecker** [comment]
Thank you, @olach! I did have a quick look at CSS grid, hoping something like that would be possible. I didn't see this example, though. This looks perfect!

**Comment by olach** [comment]
Yeah CSS grids is the future. :) A simple fallback for older browsers would be something like this:

```css
.a-selector-for-your-items {
    float: left;
    width: 200px;
    max-width: 100%;
}
```

**Comment by jenstornell** [comment]
I read about it but I'm not sure about browser support of the `minmax()` thing. In general grid now have a decent browser support: http://caniuse.com/#feat=css-grid. Only Edge is missing, but I know no one that uses that browser anyway.

But if it works with like Safari, Chrome and Firefox, I vote for trying it out. I think the browser probably solves it better than a js plugin. It also mean one less script to load.

So, good findings @olach.

**Comment by olach** [comment]
@jenstornell Edge will have full support in the next version. But my simple fallback above would be good enough for the few browsers that don't support it.

**Comment by medienbaecker** [comment]
The initial rewrite using CSS grid works great already: https://github.com/medienbaecker/kirby-images/tree/css-rewrite

All without a single media query.

![r2](https://user-images.githubusercontent.com/7975568/27691538-9bd2fcce-5ce4-11e7-85ff-2952ebf375c2.gif)


Now I will have a look at the fallback for older browsers.

**Comment by jenstornell** [comment]
It looks awesome so far. Let me know when it's out and ready for like Engineer and I will try it out then.

**Comment by jenstornell** [comment]
![image](https://user-images.githubusercontent.com/927011/27691971-d5d263d2-5ce5-11e7-9740-2d76035d2db6.png)

It now works great in Engineer. I took just a part of the screen in the screenshot above. You can close it when you tested the browser support. 👍
