### ISSUE TITLE
Caption functionality

### ISSUE THREAD

**Issue by AndyMBridges** [medienbaecker/kirby-images#25]
Hi Guys,

Any idea on how to add caption functionality? I would like to have the ability to set captions for each image in the admin panel and display them on the front end. 

Has this already been done somewhere? Am I being blind?

Thanks,
Andy

**Comment by tristantbg** [comment]
Add a caption field:
https://getkirby.com/docs/panel/blueprints/file-settings

**Comment by medienbaecker** [comment]
If you use something like that to add a `caption` field to your file fields...

```
files:
  fields:
    caption:
      label: Caption
      type: textarea
```

...you can display them on the front end like that:

```
<?php foreach($page->slideshow()->yaml() as $image): ?>   
  <?php if($image = $page->image($image)): ?>
    <figure>
      <?= $image->crop(1200,500)->html(); ?>  	
      <figcaption><?= $image->caption()->kt() ?></figcaption>
    </figure>
  <?php endif ?>
<?php endforeach; ?>
```

**Comment by AndyMBridges** [comment]
Great, thanks!
