### ISSUE TITLE
Long filenames breaks the grid

### ISSUE THREAD

**Issue by olach** [medienbaecker/kirby-images#26]
See screenshot where long filenames breaks the grid:

![images grid](https://user-images.githubusercontent.com/1300644/29027663-ec26f5a2-7b81-11e7-8856-748cc8e2dfb4.png)

The solution is to add `min-width: 0;` or `overflow: hidden;` to the `.images-item` class selector. The reason is that according to the spec, a grid item cannot by default be smaller than the size of its content.

Further reading here:
https://stackoverflow.com/questions/43311943/prevent-grid-items-from-stretching-in-css-grid-layout/43312314#43312314

**Comment by medienbaecker** [comment]
Thanks a lot @olach!
I could not reproduce this issue in Chrome, but after looking at it in Safari I can see what you mean. I just pushed the commit with `overflow: hidden` and `min-width: 0` to fix this. Thank you!

**Comment by olach** [comment]
Thanks! Yes, sorry, I forgot to mention that it was in Safari I saw this.
