### ISSUE TITLE
CSS and JS not loaded in panel

### ISSUE THREAD

**Issue by Michkkael** [medienbaecker/kirby-images#31]
I wanted to use your plugin but I have an issue. I think css and js of the plugin are not loaded. 
For installation, I just moved plugin folder into 'site/plugins/' and renamed it into 'images'. 

Do you have any idea?

This is what I get in panel :
<img width="623" alt="capture d ecran 2017-08-18 a 19 32 23" src="https://user-images.githubusercontent.com/8982274/29470302-21b0700e-844c-11e7-9a8a-64b01f8508c7.png">

**Comment by medienbaecker** [comment]
I'm not sure why the plugin assets could not be loaded. What version of Kirby do you use? Do you see anything suspicious in the Developer Tools/Console?

**Comment by Michkkael** [comment]
Ok, I finally managed to make it work!
I got this issue because I did this:
- I created a structure field named 'showcase':
```
 showcase:
    label: Images
    type: structure
    fields:
      image:
        label: Image
        type: image
```
- I stored images in this structure
- I changed type of 'showcase' to 'images'

Now, in content folder if I remove all data of old structure field, your images field is working 👍 
Maybe you could do something to prevent this kind of issue?
Thank you for your time!

**Comment by Michkkael** [comment]
(forgot to close)
