### ISSUE TITLE
Limit option

### ISSUE THREAD

**Issue by medienbaecker** [medienbaecker/kirby-images#33]

**Comment by medienbaecker** [comment]
@lukaskleinschmidt I just published a new branch for this feature:
https://github.com/medienbaecker/kirby-images/tree/feature/limit#limit-the-number-of-images

Right now it just disables the drag-and-drop functionality and hides the add button when the limit is reached. This is identical to how the structure field handles it. Do you think an additional notification/error is necessary?

**Comment by lukaskleinschmidt** [comment]
Actaully I think the disabled button and functionality should be enough.
But perhaps an indicator like this could make things more clear for the end user.
![Limit](https://camo.githubusercontent.com/3897b7543bd99c5bb8f8f13147826772d24bf5cd/687474703a2f2f6769746875622e6b6c65696e7363686d6964742e61742f6b697262792d736f727461626c652f6d6f64756c65732f6c696d69742e706e67)

**Comment by medienbaecker** [comment]
Thanks for your help, Lukas! That indicator is actually a really good idea. I just added one:

![bildschirmfoto 2017-09-02 um 16 15 30](https://user-images.githubusercontent.com/7975568/29996182-fea9bfa2-8ff9-11e7-8427-8b856dbf92f3.png)
