### ISSUE TITLE
foreach first() and offset(1)

### ISSUE THREAD

**Issue by BlueberryPuppyKisses** [medienbaecker/kirby-images#36]
I just switched from using Structure Field to [Kirby Images Plugin](https://github.com/medienbaecker/kirby-images).

Below is my code before the switch. It is for a slideshow gallery, where the order is: 
`Image Slide -> Text slide -> The rest of the images as slides`

    <?php $image = $page->imageSelection()->toStructure()->first() ?>
    <div class="div"><img data-src="<?= $image->name()->toFile()->url() ?>" class="lazy"></div>

    <?php if($page->description()->isNotEmpty()): ?>
    <div class="div"><?php echo $page->description()->kirbytext() ?></div>
    <?php endif ?>

    <?php foreach($page->imageSelection()->toStructure()->offset(1) as $image): ?>
    <div class="div"><img data-src="<?= $image->name()->toFile()->url() ?>" class="lazy"></div>
    <?php endforeach ?>

I've implemented the plugin using the sample code from github:

    <?php foreach($page->slideshow()->yaml() as $image): ?>   
      <?php if($image = $page->image($image)): ?>
        <?= $image->url(); ?>  		    
      <?php endif ?>
    <?php endforeach; ?>

which works, but doesn't with `->first()` and `->offset(1)`. 

How can I get the first and rest of the slides from the slideshow, so I can sneak in between the text slide?

**Comment by tristantbg** [comment]
You can't use structure method on an array.

```
$images = $page->slideshow()->yaml();

// First element
$images[0]

// All without the first
$images_but_the_first = array_slice($images, 1);
```

You can also try to convert the array to a structure : 

`$images = structure($page->slideshow()->yaml());`

**Comment by BlueberryPuppyKisses** [comment]
The structure code was just to give you an idea how the order was made before working with the plugin. Thanks for the help, works like a charm :)
