### ISSUE TITLE
Undefined offset: 0

### ISSUE THREAD

**Issue by Jonnotie** [medienbaecker/kirby-images#37]
For some reason after installing this plugin I get this error instead of seeing images :)

![screen shot 2017-10-27 at 14 03 22](https://user-images.githubusercontent.com/4079/32083516-9b3945e0-bb1f-11e7-819f-f1afcfed2926.png)

**Comment by Jonnotie** [comment]
Ah I think I know what happened. I used another thing with the same name in the blueprint, saved it, and then changed the type to 'images'. So I think the old thing and new thing are clashing. Other pages seems to be working.

**Comment by medienbaecker** [comment]
Yes, it looks like the images field had some old data from another field that completely confused it. Glad you figured it out!
