### ISSUE TITLE
Idea: Using Shopify Draggable instead of jQuery UI

### ISSUE THREAD

**Issue by tristantbg** [medienbaecker/kirby-images#38]
https://shopify.github.io/draggable/

**Comment by samnabi** [comment]
What are the advantages?

**Comment by tristantbg** [comment]
Cons:
jQuery UI is already included in Kirby Panel

Pro:
Better handling of dragging (there are still bugs when dragging images sometimes)
Modern and powerful
Free of use (unlike GSAP draggable)

**Comment by samnabi** [comment]
If jQuery UI is already included in the Panel, I don't see a need to introduce another dependency. Just my two cents.
