### ISSUE TITLE
Temporarily save content

### ISSUE THREAD

**Issue by medienbaecker** [medienbaecker/kirby-images#4]
Right now the defined images are lost when reloading or editing an image.

**Comment by janstieler** [comment]
Did you save the article with this field before you editing a picture?
kirby has this nice feature to say there is something to save before you leave the site. Eventually you could call this function bevor the site will leave for editing. But I don't know how that function works.
Cheers

**Comment by medienbaecker** [comment]
Thanks @janstieler, that's exactly the function I meant. I found the solution in this thread: https://forum.getkirby.com/t/how-to-keep-state-of-custom-field-in-panel-after-page-reload/4576/5

...and pushed a commit. It now keeps the changes.
