### ISSUE TITLE
Showing first image only in template

### ISSUE THREAD

**Issue by studiolathe** [medienbaecker/kirby-images#40]
Hi there,

Great plugin by the way :)

I'm just looking to show the first image in the gallery from a 'Project' page on the homepage template but the first() helper is returning error 'Call to a member function first() on string'. I understand this is because the gallery content YAML-structured by can't seem to work it out.

Template conde below:
```
<?php foreach(page('projects')->children()->visible()->shuffle() as $project): ?>
   <?php foreach($project->gallery()->yaml()->first as $image): ?>
      <?php if($image = $project->image($image)): ?>
       <img src"<?php echo $image->url(); ?>"
      <?php endif ?>
  <?php endforeach ?>
<?php endforeach ?>
```

What is the best way to approach this?

Thanks in advance.

**Comment by medienbaecker** [comment]
I think `->yaml()` creates an array and you can only use `->first()` on Kirby collections.

Can you try the following?

```
<?php foreach(page('projects')->children()->visible()->shuffle() as $project): ?>
      <?php if($image = $project->image($project->gallery()->toStructure()->first())): ?>
      <?php echo $image->html() ?>
      <?php endif ?>
<?php endforeach ?>
```

**Comment by studiolathe** [comment]
Ah perfect! Worked a charm.

Thanks for the quick response.
