### ISSUE TITLE
Compatibility with 2.5.5?

### ISSUE THREAD

**Issue by louiswalch** [medienbaecker/kirby-images#50]
Does this work with Kirby 2.5.5, it doesn't appear to be behaving correctly. My page has a 'images' field as the very last field, when viewing edit page the top of the page renders what looks like the contents of this field without any CSS.

![panel](https://user-images.githubusercontent.com/286013/40253920-9784a8ce-5aaf-11e8-92fa-a061704745c4.png)

**Comment by medienbaecker** [comment]
This definitely doesn't look right. I think it should be compatible with 2.5.5.
Did you put it into the `site/plugins` folder? It looks like the CSS is missing.

**Comment by louiswalch** [comment]
Hello, yes I placed the entire folder inside my plugins directory. When checking page source, your CSS is not being added. Do you know why that could be?

![images](https://user-images.githubusercontent.com/286013/40318483-c8c6dd40-5cf2-11e8-887b-fb8a09019091.png)

**Comment by janstieler** [comment]
I had this problem also on the first load.
After i reloaded the panel site the problem was gone.
