### ISSUE TITLE
"Add" select alternative

### ISSUE THREAD

**Issue by medienbaecker** [medienbaecker/kirby-images#6]
I do not really like the boring, not really intuitive select box when manually adding an image. Especially when there are a lot of images on a page it won't work well.

There are some possible solutions:

**Comment by medienbaecker** [comment]
Open a modal containing a similar image view for all images that are not selected.

**Comment by medienbaecker** [comment]
Duplicate the image sidebar.

**Comment by medienbaecker** [comment]
Remove the "Add" button altogether.

**Comment by medienbaecker** [comment]
Temporarily list all images in the field with "select" checkboxes.

**Comment by medienbaecker** [comment]
Leave the boring select box.

**Comment by medienbaecker** [comment]
![imagechooser](https://cloud.githubusercontent.com/assets/7975568/24505483/50f8806a-155a-11e7-8f76-58ea7e95dc9f.png)

I'll probably do something like that. Not sure how to display this modal in a structure modal yet.

**Comment by samnabi** [comment]
I think it's fine to leave the boring select box, maybe upgrading it to include a small thumbnail. But I don't think a modal is necessary.
