### ISSUE TITLE
Add the first entry?

### ISSUE THREAD

**Issue by jenstornell** [medienbaecker/kirby-images#9]
I've still not tried it out but by the screenshot it looks like it does not include an add in the "No entries yet". I think "Add a first entry" is nice in the structure field. Maybe just duplicate it?

![image](https://cloud.githubusercontent.com/assets/927011/25738863/9b8b707e-317f-11e7-815b-04e55e582f38.png)

**Comment by medienbaecker** [comment]
As I mentioned in issue https://github.com/medienbaecker/kirby-images/issues/1 the "No entries yet" text is not ideal. I want to encourage the user to drag images. The (+) Add Button is only there for usage inside of modal windows.

Maybe similar to that?

![bildschirmfoto 2017-05-05 um 12 21 43](https://cloud.githubusercontent.com/assets/7975568/25741946/6d65ddf2-318d-11e7-9fd4-3d6d0ce7c8f4.png)

**Comment by jenstornell** [comment]
Oh yes. I really like the dashed square. The only downside would be that in case of translations, you need to add that to the plugin instead, but because the structure text is not perfect I think you have figured out the right approach. 👍
